const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const db = require('./database');

console.log('\n🌱 Inicializando base de datos de Espacios Zen...\n');

// ── Usuarios Admin ─────────────────────────────────────────────────────────────
const adminPasswordHash = bcrypt.hashSync('Zen2024Admin', 10);

const users = [
  {
    id: uuidv4(),
    name: 'Zabdiel Córdova Alejandro',
    email: 'admin@espacioszen.mx',
    password: adminPasswordHash,
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
];

// ── Categorías ─────────────────────────────────────────────────────────────────
const categories = [
  { id: 'cat-cocina', name: 'Cocina', slug: 'cocina', icon: '🍳', color: '#E8F5E9', description: 'Organizadores para tu cocina', order: 1, active: true },
  { id: 'cat-recamara', name: 'Recámara', slug: 'recamara', icon: '🛏️', color: '#FFF3E0', description: 'Soluciones para tu cuarto', order: 2, active: true },
  { id: 'cat-sala', name: 'Sala', slug: 'sala', icon: '🛋️', color: '#E3F2FD', description: 'Organiza tu sala con estilo', order: 3, active: true },
  { id: 'cat-oficina', name: 'Oficina', slug: 'oficina', icon: '💼', color: '#F3E5F5', description: 'Espacio de trabajo funcional', order: 4, active: true },
  { id: 'cat-bano', name: 'Baño', slug: 'bano', icon: '🚿', color: '#E0F2F1', description: 'Organización para tu baño', order: 5, active: true },
  { id: 'cat-general', name: 'General', slug: 'general', icon: '🏠', color: '#FAFAFA', description: 'Soluciones para todo el hogar', order: 6, active: true },
];

// ── Productos ─────────────────────────────────────────────────────────────────
const products = [
  {
    id: uuidv4(),
    name: 'Kit Organizador de Cajones Premium',
    slug: 'kit-organizador-cajones-premium',
    price: 249,
    originalPrice: 299,
    categoryId: 'cat-cocina',
    description: 'Set de 8 organizadores modulares para cajones de cocina. Fabricados en plástico ABS libre de BPA. Incluye diferentes tamaños para cubiertos, utensilios y accesorios de cocina. Fáciles de limpiar y adaptar.',
    features: ['8 piezas modulares', 'Material libre de BPA', 'Fácil limpieza', 'Antideslizante en base', 'Color bambú natural'],
    rating: 4.8,
    reviewCount: 24,
    stock: 15,
    badge: 'Más vendido',
    active: true,
    featured: true,
    gradient: 'from-green-100 to-emerald-200',
    emoji: '🍴',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Especiero Giratorio Doble Nivel',
    slug: 'especiero-giratorio-doble-nivel',
    price: 389,
    originalPrice: null,
    categoryId: 'cat-cocina',
    description: 'Especiero giratorio de dos pisos con capacidad para 24 frascos. Base giratoria 360° para acceso fácil. Fabricado en acero inoxidable y plástico premium. Ahorra espacio en tu alacena o encimera.',
    features: ['24 frascos incluidos', 'Giro 360°', 'Acero inoxidable + plástico', '2 niveles independientes', 'Fácil montaje'],
    rating: 4.9,
    reviewCount: 18,
    stock: 10,
    badge: 'Nuevo',
    active: true,
    featured: true,
    gradient: 'from-yellow-100 to-amber-200',
    emoji: '🧂',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Set Cajas Decorativas Zen (3 pzas)',
    slug: 'set-cajas-decorativas-zen',
    price: 350,
    originalPrice: 420,
    categoryId: 'cat-sala',
    description: 'Set de 3 cajas organizadoras apilables con diseño minimalista. Ideales para sala o recámara. Fabricadas en tela tejida natural con estructura rígida interna. Perfectas para mantas, cojines y accesorios.',
    features: ['3 tamaños diferentes', 'Tela tejida natural', 'Estructura rígida', 'Asas de cuero sintético', 'Apilables'],
    rating: 4.7,
    reviewCount: 31,
    stock: 20,
    badge: '17% OFF',
    active: true,
    featured: true,
    gradient: 'from-orange-100 to-amber-200',
    emoji: '📦',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Organizador de Ropa Plegable XL',
    slug: 'organizador-ropa-plegable-xl',
    price: 290,
    originalPrice: null,
    categoryId: 'cat-recamara',
    description: 'Organizador tipo caja para ropa, sábanas y blancos. Plegable y fácil de guardar cuando no se usa. Ideal para armarios y clósets pequeños. Material Oxford resistente con cierre y ventana transparente.',
    features: ['Plegable y compacto', 'Tela Oxford resistente', 'Ventana transparente', 'Cierre con cremallera', 'Múltiples usos'],
    rating: 4.6,
    reviewCount: 42,
    stock: 25,
    badge: null,
    active: true,
    featured: false,
    gradient: 'from-purple-100 to-violet-200',
    emoji: '👕',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Organizador de Escritorio Modular',
    slug: 'organizador-escritorio-modular',
    price: 480,
    originalPrice: 550,
    categoryId: 'cat-oficina',
    description: 'Sistema modular de organización para escritorio. Incluye porta-lapiceros, bandeja para documentos, cajón pequeño y espacio para gadgets. Fabricado en bambú natural certificado. Diseño minimalista y elegante.',
    features: ['Bambú certificado', '5 compartimentos', 'Módulos apilables', 'Acabado natural', 'Sostenible'],
    rating: 4.9,
    reviewCount: 15,
    stock: 8,
    badge: 'Premium',
    active: true,
    featured: true,
    gradient: 'from-stone-100 to-amber-100',
    emoji: '✏️',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Set Organizadores de Baño (5 pzas)',
    slug: 'set-organizadores-bano',
    price: 320,
    originalPrice: null,
    categoryId: 'cat-bano',
    description: 'Set completo de 5 organizadores para baño. Incluye porta-cepillos, jabonera, vaso, porta-objetos y dispensador de jabón. Material: plástico ABS resistente a la humedad. Diseño nórdico minimalista.',
    features: ['5 piezas coordinadas', 'Resistente a humedad', 'Diseño nórdico', 'Fácil limpieza', 'Color blanco mate'],
    rating: 4.5,
    reviewCount: 28,
    stock: 18,
    badge: null,
    active: true,
    featured: false,
    gradient: 'from-cyan-100 to-teal-200',
    emoji: '🚿',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Repisa Flotante de Bambú Natural',
    slug: 'repisa-flotante-bambu-natural',
    price: 550,
    originalPrice: 650,
    categoryId: 'cat-general',
    description: 'Repisa flotante fabricada en bambú macizo natural. Disponible en 60cm y 80cm. Incluye kit de instalación completo. Ideal para baño, cocina, sala o recámara. Soporta hasta 10kg. Tratamiento anti-humedad.',
    features: ['Bambú macizo', 'Anti-humedad', 'Soporta 10kg', 'Kit instalación incluido', 'Disponible en 2 tamaños'],
    rating: 4.8,
    reviewCount: 19,
    stock: 12,
    badge: '15% OFF',
    active: true,
    featured: true,
    gradient: 'from-green-100 to-lime-200',
    emoji: '🪵',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Kit Colgadores Adhesivos Premium (12 pzas)',
    slug: 'kit-colgadores-adhesivos-premium',
    price: 180,
    originalPrice: null,
    categoryId: 'cat-general',
    description: 'Set de 12 colgadores adhesivos de alta resistencia. Sin perforar paredes. Soportan hasta 5kg cada uno. Incluye ganchos dobles y simples en diferentes tamaños. Removibles sin dañar pintura.',
    features: ['12 piezas surtidas', 'Sin perforar', 'Hasta 5kg cada uno', 'Removibles', 'Para múltiples superficies'],
    rating: 4.4,
    reviewCount: 56,
    stock: 30,
    badge: 'Popular',
    active: true,
    featured: false,
    gradient: 'from-slate-100 to-gray-200',
    emoji: '🪝',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Organizador Magnético para Especias',
    slug: 'organizador-magnetico-especias',
    price: 460,
    originalPrice: 520,
    categoryId: 'cat-cocina',
    description: 'Sistema de organización magnético para refrigerador. Incluye 6 frascos con tapa magnética + 2 pequeñas repisas magnéticas. Perfecto para optimizar el espacio de tu cocina. Frascos herméticos.',
    features: ['6 frascos herméticos', '2 repisas magnéticas', 'Adhiere en refrigerador', 'Acero inoxidable', 'Fácil instalación'],
    rating: 4.7,
    reviewCount: 22,
    stock: 9,
    badge: '12% OFF',
    active: true,
    featured: false,
    gradient: 'from-red-100 to-rose-200',
    emoji: '🧲',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Cesta Organizadora Natural Grande',
    slug: 'cesta-organizadora-natural-grande',
    price: 380,
    originalPrice: null,
    categoryId: 'cat-sala',
    description: 'Cesta tejida a mano en fibra natural. Perfecta para mantas, juguetes, revistas o plantas. Tamaño grande (40x35cm). Con asa de cuero genuino. Diseño artesanal estilo boho-zen. Única en su kind.',
    features: ['Tejida a mano', 'Fibra natural', 'Asa de cuero genuino', '40x35cm', 'Diseño artesanal'],
    rating: 4.9,
    reviewCount: 33,
    stock: 7,
    badge: 'Artesanal',
    active: true,
    featured: true,
    gradient: 'from-amber-100 to-yellow-200',
    emoji: '🧺',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Organizador Bajo Lavabo con Ruedas',
    slug: 'organizador-bajo-lavabo-ruedas',
    price: 420,
    originalPrice: 480,
    categoryId: 'cat-cocina',
    description: 'Sistema organizador para el espacio bajo el fregadero o lavabo. Con ruedas deslizantes para fácil acceso. 2 niveles ajustables. Fabricado en acero cromado resistente. Incluye 2 canastas laterales removibles.',
    features: ['Ruedas deslizantes', '2 niveles ajustables', 'Acero cromado', '2 canastas laterales', 'Fácil instalación'],
    rating: 4.6,
    reviewCount: 17,
    stock: 11,
    badge: '13% OFF',
    active: true,
    featured: false,
    gradient: 'from-blue-100 to-sky-200',
    emoji: '🗄️',
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Set Separadores de Cajones Flexibles',
    slug: 'set-separadores-cajones-flexibles',
    price: 159,
    originalPrice: null,
    categoryId: 'cat-recamara',
    description: 'Set de 6 separadores ajustables y flexibles para cajones. Sirve para cajones de 25cm a 65cm de largo. Material: plástico resistente con sistema de fijación por presión. Sin herramientas necesarias.',
    features: ['6 separadores', 'Ajustables 25-65cm', 'Sin herramientas', 'Plástico resistente', 'Varios colores'],
    rating: 4.3,
    reviewCount: 48,
    stock: 35,
    badge: null,
    active: true,
    featured: false,
    gradient: 'from-pink-100 to-rose-200',
    emoji: '📐',
    createdAt: new Date().toISOString(),
  },
];

// ── Pedidos de ejemplo ─────────────────────────────────────────────────────────
const orders = [
  {
    id: uuidv4(),
    orderNumber: 'ZEN-001',
    customerName: 'María García López',
    customerEmail: 'maria.garcia@email.com',
    customerPhone: '993 456 7890',
    customerAddress: 'Col. Tamulté de las Barrancas, Villahermosa, Tab.',
    items: [
      { productId: products[0].id, productName: products[0].name, quantity: 2, price: 249 },
      { productId: products[2].id, productName: products[2].name, quantity: 1, price: 350 },
    ],
    subtotal: 848,
    total: 848,
    status: 'entregado',
    notes: 'Por favor entregar en horario matutino',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uuidv4(),
    orderNumber: 'ZEN-002',
    customerName: 'Carlos Martínez Ruiz',
    customerEmail: 'carlos.mtz@gmail.com',
    customerPhone: '993 321 9876',
    customerAddress: 'Fraccionamiento Carrizal, Villahermosa, Tab.',
    items: [
      { productId: products[4].id, productName: products[4].name, quantity: 1, price: 480 },
    ],
    subtotal: 480,
    total: 480,
    status: 'enviado',
    notes: '',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uuidv4(),
    orderNumber: 'ZEN-003',
    customerName: 'Ana Torres Díaz',
    customerEmail: 'ana.torres@hotmail.com',
    customerPhone: '993 111 2233',
    customerAddress: 'Col. Atasta, Villahermosa, Tab.',
    items: [
      { productId: products[5].id, productName: products[5].name, quantity: 1, price: 320 },
      { productId: products[7].id, productName: products[7].name, quantity: 2, price: 180 },
    ],
    subtotal: 680,
    total: 680,
    status: 'procesando',
    notes: 'Regalo, incluir bolsa',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uuidv4(),
    orderNumber: 'ZEN-004',
    customerName: 'Roberto Pérez Sánchez',
    customerEmail: 'rperez@empresa.com',
    customerPhone: '993 654 3210',
    customerAddress: 'Av. Paseo Usumacinta 120, Villahermosa, Tab.',
    items: [
      { productId: products[1].id, productName: products[1].name, quantity: 1, price: 389 },
      { productId: products[9].id, productName: products[9].name, quantity: 1, price: 380 },
    ],
    subtotal: 769,
    total: 769,
    status: 'nuevo',
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ── Guardar en base de datos ───────────────────────────────────────────────────
db.replaceCollection('users', users);
db.replaceCollection('categories', categories);
db.replaceCollection('products', products);
db.replaceCollection('orders', orders);
db.replaceCollection('contacts', []);

console.log('✅ Usuarios creados:    ', users.length);
console.log('✅ Categorías creadas:  ', categories.length);
console.log('✅ Productos creados:   ', products.length);
console.log('✅ Pedidos de ejemplo:  ', orders.length);
console.log('\n🔑 Credenciales de acceso:');
console.log('   Email:     admin@espacioszen.mx');
console.log('   Contraseña: Zen2024Admin');
console.log('\n🚀 ¡Base de datos lista! Ejecuta: npm run dev\n');
